FROM node:20-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Cache package dependencies
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# Expose React Dev Port
EXPOSE 3000

# Start hot-reloading development server
CMD ["pnpm", "run", "dev"]
